name: Build and Test Pipeline

on: push

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Repo auschecken
        uses: actions/checkout@v4
      
      - name: Docker installieren
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
      
      - name: Docker-Image bauen
        run: docker build -t oldschool-demo-image-${{ github.run_number }} .
      
      - name: Container starten & testen
        run: |
          output=$(docker run oldschool-demo-image-${{ github.run_number }})
          echo "$output"
          if [ "$output" != "DEINE_INDIVIDUELLE_NACHRICHT" ]; then
            echo "Test fehlgeschlagen!"
            exit 1
          fi
          echo "Test erfolgreich!"
