name: Build and Test Pipeline

on: push

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Repo auschecken
        uses: actions/checkout@v4
      
      - name: Docker installieren
        run: |
          15| sudo apt-get update
          16| sudo apt-get install -y ca-certificates curl gnupg
          17| curl -fsSL https://get.docker.com -o get-docker.sh
          18| sh get-docker.sh
      
      - name: Docker-Image bauen
        run: docker build -t oldschool-demo-image-${{ github.run_number }} .
      
      - name: Container starten & testen
        run: |
          output=$(docker run oldschool-demo-image-${{ github.run_number }})
          echo "$output"
          if [ "$output" != "OldSchool GmbH – automatischer Build erfolgreich! (Max M.)" ]; then
            echo "❌ Test fehlgeschlagen!"
            exit 1
          fi
          echo "✅ Test erfolgreich!"
